apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mychart.fullname" . }}-mariadb
  labels:
    app.kubernetes.io/name: {{ include "mychart.name" . }}-mariadb
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ include "mychart.chart" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  database-name: {{ .Values.database.databasename | b64enc }}
  database-password: {{ .Values.database.databasepassword | b64enc }}
  database-root-password: {{ .Values.database.databaserootpassword | b64enc }}
  database-user: {{ .Values.database.databaseuser | b64enc }}
