apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mychart.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-mariadb
  labels:
    app.kubernetes.io/name: {{ include "mychart.name" . }}-mariadb
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ include "mychart.chart" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: 3306
      targetPort: mariadb
      protocol: TCP
      name: mariadb
  selector:
    app.kubernetes.io/name: {{ include "mychart.name" . }}-mariadb
    app.kubernetes.io/instance: {{ .Release.Name }}
  clusterIP: None
